# https://travis-ci.org/account/repositories

language: python

install:
  - sudo apt-get update
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda config --add channels conda-forge
  - conda config --add channels openbabel
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a

  # Replace dep1 dep2 ... with your dependencies
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION _libgcc_mutex assimulo backcall bzip2 ca-certificates cairo certifi cycler dbus expat fontconfig freetype gettext glib gst-plugins-base gstreamer icu jpeg kiwisolver libblas libcblas libedit libffi libgcc-ng libgfortran-ng libiconv liblapack libopenblas libpng libstdcxx-ng libuuid libxcb libxml2 matplotlib metis ncurses numpy openbabel openssl pcre pip pixman pthread-stubs pyparsing pyqt python-dateutil pytz qt readline requests scipy setuptools sip six sqlite suitesparse sundials tbb tk tornado wheel xorg-kbproto xorg-libice xorg-libsm xorg-libx11 xorg-libxau xorg-libxdmcp xorg-libxext xorg-libxrender xorg-renderproto xorg-xextproto xorg-xproto xz zlib
  
  - conda activate test-environment
  - python setup.py install
script: python PyCHAM/PyCHAM_CI_test.py